services:
  alice:
    build: .
    ports:
      - 5000:5000
  bob:
    build: .
    ports:
      - 5010:5000
  carol:
    build: .
    ports:
      - 5020:5000
  david:
    build: .
    ports:
      - 5030:5000

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    profiles:
      - with-ngrok
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    links:
      - alice
      - bob
      - carol
      - david
